---
title: "Minimum Requirements for metadata schemes based on mdScheme"
output: github_document
---
## One tab named `Experiment`
* horizontal layout
* only one value per property allowed

## One tab named `DataFileMetaData`
* one column named `dataFileName`


## ID field
If the first column in tab contains a field named `...ID` it will be used as grouping for xml export
Applies to all tabs except `Experiment`

## Done
- [X] as.plantuml.mdSchemeData.R --> as.plantuml.emeSchemeData.R
- [X] as.plantuml.emeSchemeSet.R --> as.plantuml.mdSchemeSet.R
- [X] cat_ln.R
- [ ] data.emeScheme.R
- [ ] data.emeScheme_example.R
- [ ] data.emeScheme_raw.R
- [ ] data.propSets.R
- [ ] emeSchemeToXml.R
- [ ] emeSchemeToXml.emeSchemeData.R
- [ ] emeSchemeToXml.emeSchemeData_DataExtraction.R
- [ ] emeSchemeToXml.emeSchemeData_Measurement.R
- [ ] emeSchemeToXml.emeSchemeData_Species.R
- [ ] emeSchemeToXml.emeSchemeData_Treatment.R
- [ ] emeSchemeToXml.emeSchemeSet.R
- [ ] emeSchemeVersions.R
- [X] emeScheme_extract.R --> mdScheme_extract.R
- [ ] emeScheme_split.R
- [ ] emeScheme_upgrade.R
- [ ] enter_new_metadata.R
- [ ] format_emeScheme_xlsx.R
- [ ] make_example.R
- [X] new_emeSchemeData.R
- [X] new_emeSchemeSet.R
- [ ] pkg.emeScheme.R
- [ ] print.emeSchemeData.R
- [ ] print.emeSchemeSet.R
- [ ] print.emeScheme_validation.R
- [ ] read_from_excel.R
- [ ] spreadsheet_upgrade.R
- [ ] updateFromNewSheet.R
- [ ] validate.R
- [ ] validationErrorFunctions.R
- [ ] xmlToEmeScheme.R
- [ ] xml_upgrade.R
