---
title: "Expt1 - data prep example"
author: "Owen Petchey"
date: "11/12/2018"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(tidyverse)
library(lubridate)
library(googlesheets)
library(here)
```

## Wheat seed additions data

This is not a measurement made, but rather a description of a feature of the experiment.
Is referred to on the **Experiment** sheet of the metadata Googlesheet/Excel workbook.

```{r}
wheat_seeds <- tibble(Date_time=dmy_hms(c("02-12-2018 09:00:00",
                                          "03-12-2019 09:00:00",
                                          "04-01-2019 09:00:00")),
                      Number_added=c(2, 20, 200))
write_csv(wheat_seeds, here("data/archiving_data/wheat_seed_additions.csv"))

```

## Read in the Jar to treatment mapping

```{r}
jar_trt <- read_csv(here("data/raw_data/Treatments_and_jars.csv"))
```

## Read, prepare and save the smell measurement data
  
```{r}
smell <- read_csv(here("data/raw_data/sample_code_table.csv")) %>%
  mutate(Date=dmy_hms(paste(Date, "09:00:00")),
                            Jar_ID=paste0("J-", Jar)) %>%
  left_join(jar_trt) %>%
  select(-Jar, -Sample_code, -o2_channel) %>%
  write_csv(., here("data/archiving_data/smell.csv"))
```

## Read, prepare and save the o2 measurement data


```{r}
OP_1HS <- read_delim(here("data/raw_data/OP_1HS.csv"), 
                     ";", escape_double = FALSE, trim_ws = TRUE, 
                     skip = 1) %>%
  mutate(Location="Head space") %>%
  separate(SensorName, into=c("Junk1", "Junk2"), remove=FALSE) %>%
  mutate(Jar_ID=paste0("J-", Junk2))
Diss_O2 <- OP_1HS %>%
  select(Date, Time, Jar_ID, DO=Value, Unit_1, Mode, Location) %>%
  na.omit() %>%
  mutate(DO=as.numeric(DO),
         DO=ifelse(Unit_1=="%a.s.", DO*0.21, DO),
         Unit_1=ifelse(Unit_1=="%a.s.", "%O2", Unit_1)) %>%
  filter(Unit_1=="%O2",
         DO!="---") %>%
  mutate(Date=str_replace(Date, "Dez", "Dec"),
         Date_time=dmy_hms(paste(Date, Time))) %>%
  select(-Date, -Time) %>%
  type_convert() %>%
  full_join(jar_trt)

rm(OP_1HS)


read_plus <- function(flnm) {
  read_delim(flnm, delim=";", skip=37,
             col_types = cols(.default = "c")) %>% 
    mutate(filename = flnm)
}
tbl1 <- list.files(path = here("data/raw_data/cont_o2_2/"),
                   pattern = "*.txt", 
                   full.names = T) %>% 
  map_df(~read_plus(.)) %>%
  separate(filename, into = c("junk1", "junk2"), sep="-ch") %>%
  separate(junk2, into=c("channel", "junk3")) %>%
  mutate(channel=as.numeric(channel))
auto_o2 <- tbl1
names(auto_o2) <- c("Date", "Time", "Logtime", "DO", "Phase", "Amp", "Temp", "filename", "channel", "junk2")
auto_o2 <- auto_o2 %>%
  mutate(Date_time=dmy_hms(paste(Date, Time)),
         Mode="Humid",
         Location="Liquid",
         Unit_1="%O2") %>%
  full_join(jar_trt, by=c("channel" = "o2_channel"))
auto_o2 <- select(auto_o2, Jar_ID, DO, Unit_1, Mode, Location, Date_time, Lid_Treatment, Jar_type, channel) %>%
  rename("o2_channel" = "channel")
Diss_O2 <- rbind(Diss_O2, auto_o2) %>%
  mutate(DO=as.numeric(DO)) %>%
  select(-Mode, -o2_channel)


write_csv(Diss_O2, here("data/archiving_data/dissolved_oxygen_measures.csv"))
```

