---
title: "Minimum requirements for MetaData scheme based on dmdScheme"
subtitle: "`r library(dmdScheme);paste0(scheme_active()$name, '_', scheme_active()$version)`"
author: "Rainer M Krug <Rainer.Krug@uzh.ch>"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Minimum requirements for metadatascheme based on dmdScheme}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = TRUE}
knitr::opts_chunk$set(
	echo = FALSE,
  collapse = TRUE,
  comment = "#>"
)
library(dmdScheme)
```

# Introduction

This document outlines the minimum requirements for metadata schemes derived from `dmdScheme` so that all functions in the `dmdScheme` package will work.

# Requirements

1. Tab name has to be identical to `propertySet` value (Cell `A:2` in the tab Experiment, `B:1` in other tabs)

2. One tab named `Experiment` is required
This tab is different to the others as it has
    1. horizontal layout
    2. only one value per property allowed
    3. the top-right cell, i.e. the one above the values to be entered, contains the word **DATA**, **name of the scheme** and **version of the scheme** separated by a space, e.g. **DATA emeScheme v0.9.5**
    
3. One tab named `DataFileMetaData` is required

    * one column named `dataFileName`

4. Each tab except `Experiment` and `DataFileMetaData` needs an ID field  
Applies to all tabs except `Experiment` and `DataFileMetaData

    * The first column in the tab must be a column named `...ID`.

5. The spreadsheet can contain a tab `DOCUMENTATION`
This tab can contain information for the user and will not be imported.

