#!/usr/local/bin/plantuml


@startuml


start
''''''''''''
:= Install and load the `dmdScheme` package in R
..R..
""install.packages("dmdScheme")""
""library("dmdScheme")""|
:= Start the included shiny app
..R..
""run_app()""|
''''''''''''
:= Select scheme 
..BROWSER..
""Availabe dmdSchemes"";
''''''''''''
:= Download New Scheme
..BROWSER..;
''''''''''''
repeat
  := Enter / Edit metadata in downloaded xlsx
  ..Excel, Pages, Libre Office, Google Docs, etc..;
  := Upload Spreadsheet containig Metadata
  ..BROWSER..|
  := Upload Datafiles
  ..BROWSER..|
  := Validate metadata and create report
  ..BROWSER..;
repeat while (errors or warnings?) is (yes)
-> no;
''''''''''''
:= Export Uploaded Spreadsheet to xml
..BROWSER..;
''''''''''''
stop

@enduml

