#!/usr/local/bin/plantuml

@startuml

start
''''''''''''
:= Install and load `dmdScheme` in R
..R code..
""install.packages("dmdScheme")""
""library("dmdScheme")"";
''''''''''''
:= Download dmdScheme template
..R code..
""open_new_spreadsheet(""
""    "emeScheme",""
""    file = "theNewScheme.xlsx",""
""    format = TRUE""
"")"";
''''''''''''
repeat
  := Edit spreadsheet and save the scheme in 'theNewScheme.xlsx';
repeat while (next iteration of scheme development);
-> done;
''''''''''''
:= Build scheme definition package
..R..
""scheme_make(""
""  schemeDefinition,""
""  examples = NULL,""
""  install_R_package = NULL,""
""  path = ".", overwrite = FALSE""
"")"";
''''''''''''
stop

@enduml
