#' Convert \code{emeScheme} object to XML
#'
#' Converts an \code{emeScheme} object into an xml object.
#'
#' Depending on the value of \code{file}, the function returns different results:
#' \itemize{
#'   \item{\code{file} not given: }{an \code{XMLNode} object}
#'   \item{\code{file = NULL}: }{a string characterisation of the \code{XMLNode} object}
#'   \item{\code{file = fileName}: }{saves the string characterisation of the \code{XMLNode} object to an xml file}
#' }
#' Based on David LeBauer, Carl Davidson, Rob Kooper. See \url{https://stackoverflow.com/a/27865512/632423}
#' @param x \code{emeScheme} object to be converted
#' @param tag xml tag of the root level. \bold{Has to be "emeScheme for the initial call!}
#' @param file empty, \code{NULL} or file name. See details below
#' @param output either \code{"metadata"} for export of metadata only or
#'   \code{"complete"} for export including classes et al.
#' @param confirmationCode code reported at the end of the validation report
#'   generated by using e.g. \code{validate(..., report = "html")} or any other
#'   reports. No export is possible witholut this \code{confirmationCode}
#'
#' @return dependant on the value of \code{file}. See Details
#' @importFrom digest digest
#' @export
#'
#' @examples
#'
#' ## emeSchemeToXml( emeScheme_example, "GoogleData" )
#' ## returns \code{XMLNode} object
#'
#' ## emeSchemeToXml( emeScheme_example, "GoogleData", file = NULL )
#' ## returns string representation of the \code{XMLNode} object
#'
emeSchemeToXml <- function (x, tag, file, output = "metadata", confirmationCode ) {

  if ( (confirmationCode != "secret code for testing") & (confirmationCode != digest::digest(object = x, algo = "sha1")) ) {
    stop("The supplied confirmation code is not correct. Re-generate the report from the same raw data used for this export.")
  }

  UseMethod("emeSchemeToXml", x)

}
